# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'EatToday' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'ReactiveObjC'
  pod 'Masonry'
  # Pods for EatToday

end
